version: "3.8"

services:
  aprs-weather:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aprs-weather
    env_file: .env_prod
    restart: always
    volumes:
      - ./logs:/var/log/aprs

